- name: Desplegar infraestructura completa con observabilidad
  hosts: all
  become: true

  vars_files:
    - vars.yml
    - vars.local.yml  # Añadir credenciales

  tasks:
    - name: Ejecutar role common
      ansible.builtin.include_role:
        name: common

    - name: Ejecutar role asdf
      ansible.builtin.include_role:
        name: cimon-io.asdf

    - name: Cambiar dueño del directorio .asdf
      ansible.builtin.file:
        path: /home/redmine/.asdf
        state: directory
        recurse: true
        owner: redmine
        group: redmine

    - name: Ejecutar role geerlingguy.mysql
      ansible.builtin.include_role:
        name: geerlingguy.mysql

    # Instalar OpenTelemetry Collector ANTES de Redmine
    - name: Instalar OpenTelemetry Collector
      ansible.builtin.include_role:
        name: grafana.grafana.opentelemetry_collector

    - name: Descargar e instalar redmine con instrumentación
      ansible.builtin.include_role:
        name: redmine

    - name: Ejecutar role geerlingguy.nginx
      ansible.builtin.include_role:
        name: geerlingguy.nginx