---
# Collections (van antes que roles)
collections:
  - name: grafana.grafana
    version: ">=2.0.0"

# Roles tradicionales
roles:
  - name: cimon-io.asdf
  - name: geerlingguy.mysql
  - name: geerlingguy.nginx